services:
  db:
    image: postgres:12.19
    restart: always
    shm_size: 128mb
    env_file:
      - ./.env
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /novel-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
